### PR TITLE
Normalize GitHub repository name when generating the migration script

### LINKED ISSUE #444: The command "generate-script" generates invalid commands when original repo name has invalid characters
## Description

The command "generate-script" generates invalid commands when the ADO repository name has characters that are not valid for repository names on GitHub.

## Reproduction Steps

- Create a repository on Azure DevOps and name it anything as long as the name has spaces or any other invalid character in it, for example, "Parts Unlimited".
- Run the command "ado2gh generate-script" command with the "--all" switch
- Migrate.ps1 will look like the script below
```posh
#!/usr/bin/env pwsh

# =========== Created with CLI version 0.18.0.0 ===========

function Exec {
    param (
        [scriptblock]$ScriptBlock
    )
    & @ScriptBlock
    if ($lastexitcode -ne 0) {
        exit $lastexitcode
    }
}
# =========== Organization: <ADO_ORG> ===========

# === Team Project: <ADO_ORG>/Parts Unlimited ===
Exec { ./ado2gh create-team --github-org "<GH_ORG>" --team-name "Parts Unlimited-Maintainers" }
Exec { ./ado2gh create-team --github-org "<GH_ORG>" --team-name "Parts Unlimited-Admins" }
Exec { ./ado2gh share-service-connection --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --service-connection-id "<SERVICE_CONNECTION_ID>" }

Exec { ./ado2gh lock-ado-repo --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-repo "PartsUnlimited" }
Exec { ./ado2gh migrate-repo --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-repo "PartsUnlimited" --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --wait }
Exec { ./ado2gh disable-ado-repo --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-repo "PartsUnlimited" }
Exec { ./ado2gh configure-autolink --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" }
Exec { ./ado2gh add-team-to-repo --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --team "Parts Unlimited-Maintainers" --role "maintain" }
Exec { ./ado2gh add-team-to-repo --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --team "Parts Unlimited-Admins" --role "admin" }
Exec { ./ado2gh integrate-boards --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" }
Exec { ./ado2gh download-logs --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" }
Exec { ./ado2gh rewire-pipeline --ado-org "<ADO_ORG>" --ado-team-project "Parts Unlimited" --ado-pipeline "\PartsUnlimitedE2E" --github-org "<GH_ORG>" --github-repo "Parts Unlimited-PartsUnlimited" --service-connection-id "<SERVICE_CONNECTION_ID>" }
```
- Notice the white spaces in "Parts Unlimited-PartsUnlimited" in the "--github-repo" switches all over the script
- This repo will be imported with the normalized name `Parts-Unlimited-PartsUnlimited` (without spaces and possibly other invalid characters) which is different from `Parts Unlimited-PartsUnlimited` (with spaces and possibly other invalid characters) so all the commands that use the incorrect name fail, for example, the command "configure-autolink".

image

### PR DESCRIPTION
**Pull request by martins-vds**
Fix #444 

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)

### CODE REVIEW

**Review by dylan-smith — CHANGES_REQUESTED** [review]
We should add a unit test for generate-script that has a team project with a space in it (or just modify the existing tests to cover that)

**Comment by dylan-smith** [comment]
I would also add a release note something like:

File: src/Octoshift/Extensions/StringExtensions.cs [hunk 1]
```diff
@@ -12,5 +13,7 @@ public static class StringExtensions
         public static bool HasValue(this string s) => !s.IsNullOrWhiteSpace();
 
         public static bool ToBool(this string s) => bool.TryParse(s, out var result) && result;
+
+        public static string Clean(this string s) => s.HasValue() ? Regex.Replace(s, @"[^a-z0-9_.-]+", "-", RegexOptions.Compiled | RegexOptions.CultureInvariant | RegexOptions.IgnoreCase) : string.Empty;
```
Comment (ArinGhazarian) [inline src/Octoshift/Extensions/StringExtensions.cs:17]: A few things here:
1. IMO it's better to use a more meaningful method name that is self descriptive. If I see `str.Clean()` somewhere in the code it would be impossible to understand what it does w/o looking at the implementation. A better name could be for example, `ReplaceInvalidCharacters(string replaceWith = "-")` or even `ReplaceInvalidCharactersWithDash()`.
2. The Regex can be simplified to `[^\w.-]`, then the `IgnoreCase` option can also be removed. So the entire Regex replace will look like the following:
```c#
Regex.Replace(s, "[^\w.-]", "-", RegexOptions.Compiled | RegexOptions.CultureInvariant)
```

**Review by ArinGhazarian — COMMENTED** [review]
Overall looks good. Left a comment about simplifying the `Regex` and choosing a more descriptive method name.

File: src/Octoshift/Extensions/StringExtensions.cs (hunk 1 above)
Comment (dylan-smith) [reply src/Octoshift/Extensions/StringExtensions.cs]: I pushed a commit to make these changes

**Comment by dylan-smith** [comment]
> We should add a unit test for generate-script that has a team project with a space in it (or just modify the existing tests to cover that)

I pushed a commit to add a couple unit tests

**Review by dylan-smith — APPROVED** [review]
