### PR TITLE
Fix incorrect help texts for some gei commands

### LINKED ISSUE #790: gh gi migrate-repo has a reference to BBS in aws-bucket-name parameter
## Description

`gh gei migrate-repo` command has a reference to BBS in the `aws-bucket-name` parameter

## Reproduction Steps

```cmd
$ gh gei migrate-repo --help | grep -i bbs
--aws-bucket-name <aws-bucket-name>                                  If using AWS, the name of the S3 bucket to upload the BBS archive to.
```

### PR DESCRIPTION
**Pull request by ArinGhazarian**
Fixes #790 

This PR fixes a couple of incorrect help texts for `gh gei`. 

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)
- [x] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

### CODE REVIEW

File: src/gei/Commands/MigrateRepoCommand.cs [hunk 1]
```diff
@@ -90,7 +90,7 @@ public class MigrateRepoCommand : CommandBase<MigrateRepoCommandArgs, MigrateRep
         };
         public Option<string> AwsBucketName { get; } = new("--aws-bucket-name")
         {
-            Description = "If using AWS, the name of the S3 bucket to upload the BBS archive to (Not required for GHES 3.8.0 and later)."
+            Description = "If using AWS, the name of the S3 bucket to upload the data archives to (Not required for GHES 3.8.0 and later)."
```
Comment (timrogers) [inline src/gei/Commands/MigrateRepoCommand.cs:93]: This isn't particularly related to your (correct!) change, but I guess we might as well fix it in this PR.

```suggestion
            Description = "If using AWS, the name of the S3 bucket to upload the data archives to. Not required if you are migrating from GitHub Enterprise Server 3.8.0 or later."
```

**Review by timrogers — APPROVED** [review]
Looks good to me! I think it'd be fine if this one didn't have release notes, FWIW.

File: src/gei/Commands/MigrateRepoCommand.cs (hunk 1 above)
Comment (ArinGhazarian) [reply src/gei/Commands/MigrateRepoCommand.cs]: addressed in 14c00bd287a7cb724f1f9d391be98c31d22a0144

**Review by timrogers — APPROVED** [review]
