### PR TITLE
Proper URL Encoding

### LINKED ISSUE #772: Incomplete URL escaping
## Description

Raising this as a result of migration friction. My client is migrating from ADO to GitHub using the ado2gh CLI extension. They have a project name which contains brackets, e.g. `Knowledge Management (KM)`. When parsing this project to `ado2gh` the migration fails with the following error:

```bash
[17:11] [ERROR] The source repository url https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo is invalid. Please ensure the source url you gave is correct and properly formatted.
```

If you parse in the value to `ado2gh` with the project name URL escaped as `Knowledge Management %28KM%29` then the migration completes successfully.

Presumably the fix is to change the logic in `MigrateRepoCommandHandler.cs` at line 101:

```dotnet
  private string GetAdoRepoUrl(string org, string project, string repo) => $"https://dev.azure.com/{org}/{project}/_git/{repo}".Replace(" ", "%20");
```

Although more pervasive changes might be required as other commands may be affected

## Reproduction Steps
- In Azure create a project name containing brackets i.e. `Knowledge Management (KM)`
- Use this project name as an input to `ado2gh`.
- See failure:
  ```bash
  ➜  ~ gh ado2gh migrate-repo --ado-org digimangos --ado-team-project "Knowledge Management (KM)" --ado-repo test-repo --github-org digimangos-work-dev --github-repo com.digimangos.bracket-test-2 --wait --ado-pat xxx --github-pat xxx --verbose
  \[10:53] [INFO] You are running the latest version of the ado2gh CLI [v0.31]
  [10:53] [INFO] Migrating Repo...
  [10:53] [INFO] ADO ORG: digimangos
  [10:53] [INFO] ADO TEAM PROJECT: Knowledge Management (KM)
  [10:53] [INFO] ADO REPO: test-repo
  [10:53] [INFO] GITHUB ORG: digimangos-work-dev
  [10:53] [INFO] GITHUB REPO: com.digimangos.bracket-test-2
  [10:53] [INFO] WAIT: true
  [10:53] [INFO] ADO PAT: ***
  [10:53] [INFO] GITHUB PAT: ***
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"query($login: String!) {organization(login: $login) { login, id, name } }","variables":{"login":"digimangos-work-dev"}}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC359F:4DDC105:63BD439D
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"organization":{"login":"digimangos-work-dev","id":"O_kgDOBkvtQA","name":"digimangos-work-dev"}}}
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"mutation createMigrationSource($name: String!, $url: String!, $ownerId: ID!, $type: MigrationSourceType!) { createMigrationSource(input: {name: $name, url: $url, ownerId: $ownerId, type: $type}) { migrationSource { id, name, url, type } } }","variables":{"name":"Azure DevOps Source","url":"https://dev.azure.com","ownerId":"O_kgDOBkvtQA","type":"AZURE_DEVOPS"},"operationName":"createMigrationSource"}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC36EC:4DDC28C:63BD439D
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"createMigrationSource":{"migrationSource":{"id":"MS_kgDaACRiMjcwNjc4Yy04NGVkLTRkNDQtODM5Ni1jYTZmYTQyMGY4MTc","name":"Azure DevOps Source","url":"https://dev.azure.com","type":"AZURE_DEVOPS"}}}}
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"\n                mutation startRepositoryMigration(\n                    $sourceId: ID!,\n                    $ownerId: ID!,\n                    $sourceRepositoryUrl: URI!,\n                    $repositoryName: String!,\n                    $continueOnError: Boolean!,\n                    $gitArchiveUrl: String,\n                    $metadataArchiveUrl: String,\n                    $accessToken: String!,\n                    $githubPat: String,\n                    $skipReleases: Boolean,\n                    $lockSource: Boolean) { \n                startRepositoryMigration(\n                    input: { \n                        sourceId: $sourceId,\n                        ownerId: $ownerId,\n                        sourceRepositoryUrl: $sourceRepositoryUrl,\n                        repositoryName: $repositoryName,\n                        continueOnError: $continueOnError,\n                        gitArchiveUrl: $gitArchiveUrl,\n                        metadataArchiveUrl: $metadataArchiveUrl,\n                        accessToken: $accessToken,\n                        githubPat: $githubPat,\n                        skipReleases: $skipReleases,\n                        lockSource: $lockSource\n                    }\n                ) {\n                    repositoryMigration {\n                        id,\n                        migrationSource {\n                            id,\n                            name,\n                            type\n                        },\n                        sourceUrl,\n                        state,\n                        failureReason\n                    }\n                  } }","variables":{"sourceId":"MS_kgDaACRiMjcwNjc4Yy04NGVkLTRkNDQtODM5Ni1jYTZmYTQyMGY4MTc","ownerId":"O_kgDOBkvtQA","sourceRepositoryUrl":"https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo","repositoryName":"com.digimangos.bracket-test-2","continueOnError":true,"gitArchiveUrl":null,"metadataArchiveUrl":null,"accessToken":"***","githubPat":"***","skipReleases":false,"lockSource":false},"operationName":"startRepositoryMigration"}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC3F83:4DDCB17:63BD439F
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"startRepositoryMigration":{"repositoryMigration":{"id":"RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY","migrationSource":{"id":"MS_kgDaACRiMjcwNjc4Yy04NGVkLTRkNDQtODM5Ni1jYTZmYTQyMGY4MTc","name":"Azure DevOps Source","type":"AZURE_DEVOPS"},"sourceUrl":"https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo","state":"QUEUED","failureReason":""}}}}
  [10:53] [DEBUG] HTTP POST: https://api.github.com/graphql
  [10:53] [DEBUG] HTTP BODY: {"query":"query($id: ID!) { node(id: $id) { ... on Migration { id, sourceUrl, migrationSource { name }, state, failureReason, repositoryName } } }","variables":{"id":"RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY"}}
  [10:53] [DEBUG] GITHUB REQUEST ID: 262A:A783:4CC4F24:4DDDB07:63BD43A2
  [10:53] [DEBUG] RESPONSE (OK): {"data":{"node":{"id":"RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY","sourceUrl":"https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo","migrationSource":{"name":"Azure DevOps Source"},"state":"FAILED","failureReason":"The source repository url https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo is invalid. Please ensure the source url you gave is correct and properly formatted.","repositoryName":"com.digimangos.bracket-test-2"}}}
  [10:53] [ERROR] Migration Failed. Migration ID: RM_kgDaACQ2ODU2OTE5MS1mM2VkLTQ5YjItYmNjZi0zY2I3MTRiMWEzMGY
  [10:53] [ERROR] OctoshiftCLI.OctoshiftCliException: The source repository url https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)/_git/test-repo is invalid. Please ensure the source url you gave is correct and properly formatted.
     at OctoshiftCLI.AdoToGithub.Handlers.MigrateRepoCommandHandler.Handle(MigrateRepoCommandArgs args)
     at OctoshiftCLI.Extensions.CommandExtensions.<>c__DisplayClass1_0`3.<<ConfigureCommand>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext )
     at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
  --- End of stack trace from previous location ---
     at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
  ```

### PR DESCRIPTION
**Pull request by dylan-smith**
- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)
- [x] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

Fixes #772 

We had a bunch of places in the code where we were replacing spaces in URL's with %20. The more robust way to do this is to use `HttpUtility.UrlEncode()` which will also catch other special characters (e.g. parentheses which are valid in ADO Team Project names).

I created an extension method `string.UrlEncode` to make the code a bit more concise.

Everywhere we craft a URL with user-provided values we should be calling `UrlEncode()` on the user provided values at the place in the code where we stuff them into a URL. This is alot of places in our AdoApi/GitApi/etc classes.

I updated some of our unit test sample data to have special characters, and updated the expected values in a whole whack of existing tests to give a good amount of coverage over the new behavior.

### CODE REVIEW

**Review by digimangos — COMMENTED** [review]
@dylan-smith this didn't work for my use case:

```bash
➜  net6.0 git:(dylan-smith/url-encoding) dotnet ado2gh.dll migrate-repo --ado-org digimangos --ado-team-project "Knowledge Management (KM) - Technology Roadmap" --ado-repo test-repo-Migrated --github-org digimangos-playground --github-repo character-test-1 --wait --ado-pat xxx --github-pat xxx
[11:33] [WARNING] You are not running the ado2gh CLI as a gh extension. This is not recommended, please run: gh extension install github/gh-ado2gh
[11:33] [WARNING] You are running an older version of the ado2gh CLI [v1.0.0.0]. The latest version is v0.37.
[11:33] [WARNING] Please update by running: gh extension upgrade ado2gh
[11:33] [INFO] Migrating Repo...
[11:33] [INFO] ADO ORG: digimangos
[11:33] [INFO] ADO TEAM PROJECT: Knowledge Management (KM) - Technology Roadmap
[11:33] [INFO] ADO REPO: test-repo-Migrated
[11:33] [INFO] GITHUB ORG: digimangos-playground
[11:33] [INFO] GITHUB REPO: character-test-1
[11:33] [INFO] WAIT: true
[11:33] [INFO] ADO PAT: ***
[11:33] [INFO] GITHUB PAT: ***
[11:33] [ERROR] Migration Failed. Migration ID: RM_kgDaACQ4MWQxYTk2Mi0zOTBjLTRkY2EtYmIyYi0xMzZhY2M2MWVkOTE
[11:33] [INFO] Migration log available at  or by running `gh ado2gh download-logs --github-target-org digimangos-playground --target-repo character-test-1`
[11:33] [ERROR] The source repository url https://dev.azure.com/digimangos/Knowledge+Management+(KM)+-+Technology+Roadmap/_git/test-repo-Migrated is invalid. Please ensure the source url you gave is correct and properly formatted.
```

The escaping looks wrong, shouldn't the url in the error:

```
https://dev.azure.com/digimangos/Knowledge+Management+(KM)+-+Technology+Roadmap/_git/test-repo-Migrated
```

be:

```
https://dev.azure.com/digimangos/Knowledge%20Management%20(KM)%20-%20Technology%20Roadmap/_git/test-repo-Migrated
```

File: src/Octoshift/AdoApi.cs [hunk 1]
```diff
@@ -27,7 +27,7 @@ public AdoApi(AdoClient client, string adoServerUrl, OctoLogger log)
 
         public virtual async Task<string> GetOrgOwner(string org)
         {
-            var url = $"{_adoBaseUrl}/{org}/_apis/Contribution/HierarchyQuery?api-version=5.0-preview.1";
+            var url = $"{_adoBaseUrl}/{org.UrlEncode()}/_apis/Contribution/HierarchyQuery?api-version=5.0-preview.1";
```
Comment (ArinGhazarian) [inline src/Octoshift/AdoApi.cs:30]: 1. `UrlEncode` is not what we want here (I know it is confusing), what we actually want is url escaping (or percent encoding if you will). The reason is `HttpUtility.UrlEncode()` acts a bit differently and encodes the spaces to `+` rather than percent encode to `%20`. The recommended way is to use [Uri.EscapeUriString()](https://learn.microsoft.com/en-us/dotnet/api/system.uri.escapeuristring?view=net-7.0) with `Uri.EscapeDataString()` (for escaping query paramerters).
2. In most cases with can get away with just passing the entire url into the `Uri.EscapeUriString()` except in cases where we construct the query string and it needs to be escaped in which the `Uri.EscapeDataString()` would be the recommended option (because it escapes the reserved chars too). Here is a good [SO thread](https://stackoverflow.com/questions/4396598/whats-the-difference-between-escapeuristring-and-escapedatastring) about `EscapeUriString` vs `EscapeDataString`.

**Review by ArinGhazarian — CHANGES_REQUESTED** [review]

File: src/Octoshift/AdoApi.cs (hunk 1 above)
Comment (dylan-smith) [reply src/Octoshift/AdoApi.cs:30]: That SO thread explains it well, I'll change it to EscapeDataString()

Comment (dylan-smith) [reply src/Octoshift/AdoApi.cs]: Done. Changed it to EscapeDataString everywhere I had UrlEncode

**Comment by dylan-smith** [comment]
> @dylan-smith this didn't work for my use case:
> 
> ```shell
> ➜  net6.0 git:(dylan-smith/url-encoding) dotnet ado2gh.dll migrate-repo --ado-org digimangos --ado-team-project "Knowledge Management (KM) - Technology Roadmap" --ado-repo test-repo-Migrated --github-org digimangos-playground --github-repo character-test-1 --wait --ado-pat xxx --github-pat xxx
> [11:33] [WARNING] You are not running the ado2gh CLI as a gh extension. This is not recommended, please run: gh extension install github/gh-ado2gh
> [11:33] [WARNING] You are running an older version of the ado2gh CLI [v1.0.0.0]. The latest version is v0.37.
> [11:33] [WARNING] Please update by running: gh extension upgrade ado2gh
> [11:33] [INFO] Migrating Repo...
> [11:33] [INFO] ADO ORG: digimangos
> [11:33] [INFO] ADO TEAM PROJECT: Knowledge Management (KM) - Technology Roadmap
> [11:33] [INFO] ADO REPO: test-repo-Migrated
> [11:33] [INFO] GITHUB ORG: digimangos-playground
> [11:33] [INFO] GITHUB REPO: character-test-1
> [11:33] [INFO] WAIT: true
> [11:33] [INFO] ADO PAT: ***
> [11:33] [INFO] GITHUB PAT: ***
> [11:33] [ERROR] Migration Failed. Migration ID: RM_kgDaACQ4MWQxYTk2Mi0zOTBjLTRkY2EtYmIyYi0xMzZhY2M2MWVkOTE
> [11:33] [INFO] Migration log available at  or by running `gh ado2gh download-logs --github-target-org digimangos-playground --target-repo character-test-1`
> [11:33] [ERROR] The source repository url https://dev.azure.com/digimangos/Knowledge+Management+(KM)+-+Technology+Roadmap/_git/test-repo-Migrated is invalid. Please ensure the source url you gave is correct and properly formatted.
> ```
> 
> The escaping looks wrong, shouldn't the url in the error:
> 
> ```
> https://dev.azure.com/digimangos/Knowledge+Management+(KM)+-+Technology+Roadmap/_git/test-repo-Migrated
> ```
> 
> but I think it should be:
> 
> ```
> https://dev.azure.com/digimangos/Knowledge%20Management%20%28KM%29%20-%20Technology%20Roadmap/_git/test-repo-Migrated
> ```

I think the change I just did will fix it, I'll do some manual testing before I merge this and show you the results

**Review by ArinGhazarian — APPROVED** [review]
🥇

**Review by digimangos — APPROVED** [review]
Apologies for the delay in checking, but LGTM 🚀
