### PR TITLE
Validates API Url before generating script

### LINKED ISSUE #621: `--ghes-api-url` is not validated for basic correctness when running `gh gei generate-script`
## Description

When specifying the `--ghes-api-url` option with `generate-script` to prepare a GHES ➡️ GHEC migration, the URL is not validated for basic correctness.

A badly typed or badly copy-and-pasted URL will cause the process to blow up, but you have to look at the logs to find out why.

We could instead validate the URL before trying to make any API requests and return a clear, explicit error message if it fails basic validity checks.

## Reproduction Steps

Run `gh gei generate-script` with the `--ghes-api-url` option set to an obviously invalid URL (e.g. missing a `:` separating the schema from the host)

### PR DESCRIPTION
**Pull request by hfishback01**
Closes #621 

Validates API Url before generating script. If URL is not in valid format, command will fail fast and provide appropriate error message:

Screenshot 2023-07-11 at 10 57 55 AM

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)
- [x] New package licenses are added to `ThirdPartyNotices.txt` (if applicable)

### CODE REVIEW

File: src/gei/Commands/GenerateScript/GenerateScriptCommandArgs.cs [hunk 1]
```diff
@@ -33,6 +34,17 @@ public override void Validate(OctoLogger log)
             {
                 throw new OctoshiftCliException("--ghes-api-url must be specified when --no-ssl-verify is specified.");
             }
+
+            if (!GhesApiUrl.IsNullOrWhiteSpace())
```
Comment (dylan-smith) [inline src/gei/Commands/GenerateScript/GenerateScriptCommandArgs.cs:38]:
```suggestion
            if (GhesApiUrl.HasValue())
```

**Review by synthead — APPROVED** [review]
LGTM!

**Review by synthead — APPROVED** [review]
