### PR TITLE
Print a warning when `bbs2gh migrate-repo` is run in "on the Bitbucket instance" mode, which users often do by mistake

### LINKED ISSUE #1145: BBS: Uploading migration archive to AWS without SSH should produce an error
## Description

There are a couple of issues to unpack here: 

1. Should the default assumption be that users are running the CLI commands on a BBS server? 
2. If so, there should be an error surfaced if an `--ssh-user` and `--ssh-private-key ` flags are not provided

See further discussion within [this](https://github.slack.com/archives/C02NY8K8CRY/p1697649653393449) thread. 

## Reproduction Steps

Running the following commands: 

`gh bbs2gh migrate-repo --bbs-server-url https://test-bbs-o.githubapp.com/ --bbs-project IM --bbs-repo test-commit-id-blank-review --aws-bucket-name begonabucket`

produces a successful result: 

```
[2023-10-18 09:58:20] [INFO] You are running the latest version of the bbs2gh extension [v1.2.1]
[2023-10-18 09:58:20] [INFO] BBS SERVER URL: https://test-bbs-o.githubapp.com/
[2023-10-18 09:58:20] [INFO] BBS PROJECT: IM
[2023-10-18 09:58:20] [INFO] BBS REPO: test-commit-id-blank-review
[2023-10-18 09:58:20] [INFO] AWS BUCKET NAME: begonabucket (the first one doesn't produce this ofc)
[2023-10-18 09:58:20] [INFO] SSH PORT: 22
[2023-10-18 09:58:21] [INFO] Export started. Export ID: 306
[2023-10-18 09:58:21] [INFO] Export status: RUNNING; 50% complete
[2023-10-18 09:58:32] [INFO] Export completed. Your migration archive should be ready on your instance at $BITBUCKET_SHARED_HOME/data/migration/export/Bitbucket_export_306.tar
```

This is incorrect and should have surfaced an error.

### PR DESCRIPTION
**Pull request by timrogers**
When running `bbs2gh migrate-repo`, there are a lot of different branches depending on the CLI arguments (and environment variables 😓 ) specified.

One of our branches is designed for the case where the CLI is run on the Bitbucket instance itself, where we assume that the generated migration archive is available in the local filesystem.

This branch is not usually the one that users want, but it is easy to accidentally fall into it by mistake because of the arguments you specified.

This PR introduces a new warning log if you fall into that branch to tell you that you're probably not where you intend to be, and to point you in the right direction:

> You haven't specified --ssh-user or --smb-user, so we assume that you're running the CLI on the Bitbucket instance itself. If you are not running this command on the Bitbucket instance, run this command again with the --ssh-user or --smb-user argument to allow the CLI to download the migration archive from the server.

As part of this PR, I've also made a small tweak to the existing "Export completed..." log line to clarify that the archive is now on the Bitbucket Server.

Fixes #1145.

### CODE REVIEW

File: src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs [hunk 1]
```diff
@@ -75,6 +75,11 @@ public async Task Handle(MigrateRepoCommandArgs args)
             {
                 args.ArchivePath = await DownloadArchive(exportId);
             }
+
+            if (!args.ShouldDownloadArchive() && args.ShouldUploadArchive())
```
Comment (begonaguereca) [inline src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:79]: So this definitely would prompt a user to pull in the correct arguments. I wonder if the base premise of users running this command in BBS is something we should consider first

File: src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs [hunk 2]
```diff
@@ -162,7 +167,7 @@ private async Task<long> GenerateArchive(MigrateRepoCommandArgs args)
             throw new OctoshiftCliException($"Bitbucket export failed --> State: {exportState}; Message: {exportMessage}");
         }
 
-        _log.LogInformation($"Export completed. Your migration archive should be ready on your instance at $BITBUCKET_SHARED_HOME/data/migration/export/Bitbucket_export_{exportId}.tar");
+        _log.LogInformation($"Export completed. Your migration archive should be ready **on your Bitbucket instance** at $BITBUCKET_SHARED_HOME/data/migration/export/Bitbucket_export_{exportId}.tar");
```
Comment (begonaguereca) [inline src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:170]: Love the addition of this language!

I was curious about the link provided when I first saw it printed to the console because it's clickable but doesn't (ofc) take you anywhere. Is the migration available to see in the BBS UI at all?

Comment (timrogers) [reply src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:170]: Afraid not! :(

File: src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs (hunk 1 above)
Comment (timrogers) [reply src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:79]: We definitely consider the ergonomics of the command - I do think the default is "wrong"! - but changing the behaviour is likely to be a breaking change for existing users, so we need to consider that carefully.

Given that, I think I'd choose to add a band-aid for now to stop the bleeding, and then take a step back and think about the right long-term solution.

Comment (timrogers) [reply src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:79]: Just so you know, you wouldn't get this log line in the case you ran into because you didn't specify a target GitHub organization and repo. But you could get the other log line you commented on below.

**Review by ArinGhazarian — APPROVED** [review]
Looks good 🚢 🚀

File: src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs (hunk 2 above)
Comment (begonaguereca) [reply src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:170]: Is there a reason we share this with folks then?

Comment (timrogers) [reply src/bbs2gh/Commands/MigrateRepo/MigrateRepoCommandHandler.cs:170]: We have this output because, depending on your arguments, the CLI might stop here and expect you to go to the Bitbucket instance manually to grab the archive. This tells you where the archive will be.

**Comment by timrogers** [comment]
Before merging this, I wanted to do some manual testing - and document it for future cases. `bbs2gh migrate-repo` has several different modes to test, and this can be a bit tricky!

### End-to-end mode, running on the Bitbucket instance

The CLI runs an export, downloads it from the server over SSH or SMB, uploads it to blob storage and then imports the repo to GitHub

This mode is triggered when you specify:

* A `--bbs-server-url` for running an export
* A `--ssh-user` or `--smb-user` for downloading it from the server
* A GitHub organization and repo to migrate to
* No explicit, pre-provided archive URL or path

Expected result after this PR:

* `Your migration archive should be ready **on your Bitbucket instance**` is logged ✅ 
* `You haven't specified --ssh-user or --smb-user...` is logged ✅ 

### End-to-end mode, running off the Bitbucket instance

The CLI runs an export, uploads it from the local filesystem to blob storage, and then imports the repo to GitHub

This mode is triggered when you specify:

* A `--bbs-server-url` for running an export
* No `--ssh-user` or `--smb-user` for downloading it from the server
* A GitHub organization and repo to migrate to
* No explicit, pre-provided archive URL or path

Expected result after this PR:

* `Your migration archive should be ready **on your Bitbucket instance**` is logged ✅ 
* No `You haven't specified --ssh-user or --smb-user` log ✅ 

### Export only mode

The CLI runs an export, and then stops, without doing anything with the generated export archive.

This mode is triggered when you specify:

* A `--bbs-server-url` for running an export
* No `--ssh-user` or `--smb-user` for downloading it from the server
* No GitHub organization and repo to migrate to
* No explicit, pre-provided archive URL or path

Expected result after this PR:

* `Your migration archive should be ready **on your Bitbucket instance**` is logged ✅ 
* No `You haven't specified --ssh-user or --smb-user` log ✅ 

### Export and download mode

This CLI runs an export, downloads the archive using SSH/SMB to the machine where the CLI is running, and then stops.

This mode is triggered when you specify:

* A `--bbs-server-url` for running an export
* A `--ssh-user` or `--smb-user` for downloading it from the server
* No GitHub organization and repo to migrate to
* No explicit, pre-provided archive URL or path

Expected result after this PR:

* `Your migration archive should be ready **on your Bitbucket instance**` is logged ✅ 
* No `You haven't specified --ssh-user or --smb-user` log ✅ 

### Upload and import mode

The CLI takes a local archive, uploads it to AWS or Azure, and then import the repo to GitHub

This mode is triggered when you specify:

* The path of a local archive with `--archive-path`
* The GitHub organization and repo to migrate to
* The `--bbs-server-url` (this is not used to run the export; just to figure out the correct URL of the source repo, which is required to perform the migration)
* No `--ssh-user` or `--smb-user` for downloading an archive from the server

Expected result after this PR:

* No `Your migration archive should be ready **on your Bitbucket instance**` log ✅ 
* No `You haven't specified --ssh-user or --smb-user` log ✅ 

### Import-only mode

The CLI takes an archive URL already accessible over the internet and imports it to GitHub

This mode is triggered when you specify:

* The URL of an intenret-accessible archive with `--archive-url`
* The GitHub organization and repo to migrate to
* The `--bbs-server-url` (this is not used to run the export; just to figure out the correct URL of the source repo, which is required to perform the migration)
* No `--ssh-user` or `--smb-user` for downloading an archive from the server

Expected result after this PR:

* No `Your migration archive should be ready **on your Bitbucket instance**` log ✅ 
* No `You haven't specified --ssh-user or --smb-user` log ✅
