### PR TITLE
Error out when no migratable repos

### LINKED ISSUE #448: The command "generate-script" generates empty script when there are no repos in ADO
## Description

The command "ado2gh generate-script" generates empty migration script when there are no repos in ADO or the existing ones are disabled. This usually happens when a prior migration has failed and left the repos disabled in ADO.

image

image

## Expected Behavior

- An exception with a detailed description of the problema would help instead of generating an empty script

### PR DESCRIPTION
**Pull request by ArinGhazarian**
Fixes #448 

With this PR the `generate-script` command in both `ado2gh` and `gei` will no longer create an empty script if no migratable repos were found. In that case it will spit out an error log and gracefully exits. 

- [x] Did you write/update appropriate tests
- [x] Release notes updated (if appropriate)
- [x] Appropriate logging output
- [x] Issue linked
- [x] Docs updated (or issue created)

### CODE REVIEW

File: src/ado2gh/Commands/GenerateScriptCommand.cs [hunk 1]
```diff
@@ -158,6 +158,12 @@ public async Task Invoke(GenerateScriptCommandArgs args)
             _adoInspectorService.OrgFilter = args.AdoOrg;
             _adoInspectorService.TeamProjectFilter = args.AdoTeamProject;
 
+            if (await _adoInspectorService.GetRepoCount() == 0)
+            {
+                _log.LogError("A migration script could not be generated because no migratable repos were found. Please note that the GEI does not migrate disabled and TFVC repos.");
```
Comment (dylan-smith) [inline src/ado2gh/Commands/GenerateScriptCommand.cs:163]:
```suggestion
                _log.LogError("A migration script could not be generated because no migratable repos were found. Please note that the GEI does not migrate disabled or TFVC repos.");
```

File: src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs [hunk 2]
```diff
@@ -852,10 +810,9 @@ public async Task PatallelScript_Skips_Team_Project_With_No_Repos()
             };
             await _command.Invoke(args);
 
-            _scriptOutput = TrimNonExecutableLines(_scriptOutput, 35, 6);
-
             // Assert
-            _scriptOutput.Should().BeEmpty();
+            _scriptOutput.Should().BeNull();
```
Comment (dylan-smith) [inline src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs:814]: theres a typo in the test method name above

**Review by dylan-smith — APPROVED** [review]

File: src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs (hunk 2 above)
Comment (ArinGhazarian) [reply src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs:814]: Fixed in 2f3f608394d441f9a97d5740e04e5d0fc5c35607

File: src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs [hunk 3]
```diff
@@ -269,7 +269,7 @@ public async Task SequentialScript_Skips_Team_Project_With_No_Repos()
 
             // Assert
             _scriptOutput.Should().BeNull();
-            _mockOctoLogger.Verify(m => m.LogError("A migration script could not be generated because no migratable repos were found. Please note that the GEI does not migrate disabled and TFVC repos."));
```
Comment (dylan-smith) [inline src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs]: you can leave it like this if you want, but if I was writing this test I'd just assert that something was written to the error log, not the specific message.  In general I'm not a huge fan of testing specific log output (I know you do that often, but I don't)

Comment (ArinGhazarian) [reply src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs]: I am always kinda torn, my philosophy is that the error message is part of the user experience so I add a verification to make sure that if the message changes at least a test breaks. But I also agree that it is not part of the actual functionality of a unit and does not affect the correctness of it.

Comment (dylan-smith) [reply src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs]: I also believe that some things are more valuable to test than others, and sometimes the cost of writing and maintaining a test isn't justified by the value the test provides.

Comment (ArinGhazarian) [reply src/OctoshiftCLI.Tests/ado2gh/Commands/GenerateScriptCommandTests.cs]: addressed in f56608976fee6799b938eb6d58e587ac66ce6d9f
